### PR TITLE
Contact density bins added

### PR DESCRIPTION
**Pull request by kadupitiya**
@jadhao:
PR for contact density binning.

### CODE REVIEW

**Comment by kadupitiya** [comment]
@jadhao: Please check the changes and let me know.
Thanks

**Comment by jadhao** [comment]
@kadupitiya things look ok to me. However, can you send a results for contact value density for say the default parameters. we have some old data from @nasimanousheh who can see if things are roughly the same; the sterics are little different, but at least there should be some confirmation.

**Comment by kadupitiya** [comment]
@jadhao and @nasimanousheh:
I am attaching density profiles and energy file for this update with following parameters [(default):]
time aprun -n 4 -d 16 ./md_simulation_confined_ions -Z 3 -p 1 -n -1 -c 0.5 -d 0.714 -S 1000000


[data.zip](https://github.com/softmaterialslab/nanoconfinement-md/files/2551631/data.zip)

**Comment by jadhao** [comment]
@kadupitiya approving

**Comment by jadhao** [comment]
@nasimanousheh what was the contact density you got from your past simulations for the default system -Z 3 -p 1 -n -1 -c 0.5 -d 0.714 -S 1000000, its ok if d was 0.553 nm?

**Pull request merged**
