### PR TITLE
modified the program to support the rappture

### PR DESCRIPTION
**Pull request by kadupitiya**
modified the program to support the rappture

### CODE REVIEW

**Comment by kadupitiya** [comment]
@jadhao please have a look.
Thank you!

**Comment by smarru** [comment]
@kadupitiya I think this has all your iterations from workspace. I suggest you squash all commits into one so it will be easy to review. An example is here - https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by jadhao** [comment]
@smarru we have checked the simulations on nanohub, local, and cluster...I am happy to merge it without a detailed review. do you want to do that (if yes, then we will collapse the commits as you say, otherwise I accept as is?

**Comment by smarru** [comment]
@jadhao @kadupitiya this changes are great, i also tried it on my workspace and its working well. Squashing is only to help review. If you reviewed the functionality instead, then its not needed. Thanks for checking.

**Pull request merged**
