### PR TITLE
changed to get a concise, effective outlog; suppressed file writing t…

### PR DESCRIPTION
**Pull request by jadhao**
…hat is not needed in rappture; minimum steps needs to be 20000 to enable proper equilibration

### CODE REVIEW

**Comment by kadupitiya** [comment]
@jadhao : everything looks fine.
Did you change the file name "initial_configuration.dat"?
So if user ran a simulation with steps less than 10,000, production will not happen.
Is that okay.
We may want to change the min steps in tool.xml as well.

**Comment by smarru** [comment]
@jadhao I just built your fork in my workspace https://github.com/jadhao/nanoconfinement-md/, it runs fine but the plots are empty. I will look more closely what changed.

**Comment by jadhao** [comment]
@kadupitiya yes I did change the file name
And yes, we must set 20,000 as the minimum. 10,000 is the default hit eqm for steps < 100,000. This is because system does not reach equilibrium before 10,000 for all the params.

**Comment by jadhao** [comment]
@smarru 20,000 is the minimum number of time steps; we should not go lower than this. the code was remade to reflect that. so the wrapper may need a change in the min S. then it should work.

**Comment by jadhao** [comment]
@kadupitiya @smarru please change min steps in wrapper etc. to 20000

**Comment by kadupitiya** [comment]
@jadhao Okay. I am doing the +/- combined plot. So I will add min step 20000 to tool.xml. 
Can you merge this so I can pull the latest version?

**Comment by jadhao** [comment]
verified by team

**Pull request merged**
