### PR TITLE
Added the image as instructed

### PR DESCRIPTION
**Pull request by kadupitiya**
Added the image as instructed

### CODE REVIEW

**Comment by kadupitiya** [comment]
@smarru and @jadhao : 
I have added the image.
It is showing fine and there is a small change in the layout.
You will see now we dont have two tabs for two groups of parameters.
Please have a look.
I can still show two groups as two tabs if you need it that way.
I thought it is easier this way.
Thanks

**Comment by jadhao** [comment]
@kadupitiya @smarru should I accept this and then you implement the removal of the induced density map 2d image with the one provided in the email? or should I wait?

**Comment by kadupitiya** [comment]
@jadhao  can u accept this and I will change the image and send another pull.
Thanks

**Comment by jadhao** [comment]
@kadupitiya approved.

**Pull request merged**
