### PR TITLE
Combined +/- density plots are added

### PR DESCRIPTION
**Pull request by kadupitiya**
Combined +/- density plots are added.

### CODE REVIEW

**Comment by kadupitiya** [comment]
@jadhao @smarru : I checked this and it runs fine.
Please have a look.

**Comment by jadhao** [comment]
@kadupitiya @smarru now approving this

**Comment by smarru** [comment]
it is working great. @jadhao wondering if we should make the combined plot the default? If so I can send a PR for it

**Comment by kadupitiya** [comment]
Ok.
Thank you!

**Comment by jadhao** [comment]
@kadupitiya @smarru I think we should keep it secondary. If you now play with different steps or other parameters, and then hit ALL on rappture, the figure will be very crowded. Is that not the case?

**Comment by jadhao** [comment]
@kadupitiya please reply all to geoffrey's email saying that this feature is deployed. we are deciding whether to default it or keep it secondary option

**Comment by kadupitiya** [comment]
Ok. I will do that.

**Comment by smarru** [comment]
@jadhao you are right, ALL is making it very crowded. There is color coding, but still not easy to parse visually. + 1 to keep the combined one secondary.

**Comment by kadupitiya** [comment]
@jadhao  Yeah. I also think that we can keep the combined plot as secondary option.

**Pull request merged**
