### PR TITLE
Updated Files

### PR DESCRIPTION
**Pull request by nasimanousheh**
@jadhao and @kadupitiya 
- I updated the example file for both lammps and inhouse code. Both results are for -Z 3 -p 1 -n -1 -c 0.5 -d 0.714 -S 1000000 -T 0.001 (and for 1000 frequency).
- The density profiles (with error bars) are comparable. The potential energies are comparable too. You can compare the results in example files.
- I also updated the lammps script (contribution of wall energy to the total energy and change dt).   
- In Nanoconfinement.cpp I changed the frequency from 0.01 to 0.001 (to have more samples). I also removed make_bins (it is already in Nanoconfinment.cpp) and bin_ions functions (it is already in compute_density_profile function).

### CODE REVIEW

**Comment by jadhao** [comment]
@nasimanousheh the freq default in inhouse is 100. in lammps it is 0.001 times the total number of steps = 5000 steps? So lammps sample frequency is very different than inhouse frequency. Can you make them the same? It is hard to believe that lammps is less noisy with these settings. I suggest you make them both such that the sampling frequency for density binning is 1000 steps.

**Comment by nasimanousheh** [comment]
@jadhao I updated the example file for inhouse code with sampling frequency 1000.
 **- in lammps it is 0.001 times the total number of steps = 5000 steps?**
The fequency sampling for Lammps must be 1000. (0.001 time step)* (the total number of steps 1000000) = 1000.

**Comment by jadhao** [comment]
@nasimanousheh this does fix the inhouse sampling frequency. But if you say 0.001 * total number of steps, then you get 1000 only for 1 million steps. For 5 million you will get 5000, in which case the comparison between the two approaches will not be reasonable. So you should have it static to 1000 just like the freq variable in inhouse code. Instead of passing the movie freq variable to lammps, you should pass the freq variable as the lammps movie frequency input. Then your sampling is the same no matter what steps are chosen.
When you fixed the inhouse to 1000, did the comparison become more reasonable -- it should lead to comparable errorbars?

**Comment by nasimanousheh** [comment]
Now, the error bars (for both lammps and inhouse) are comparable. Both are in order of ~0.01.
The result of inhouse with frequency sample =100 had much smaller error bars (order of ~0.001).

 **Instead of passing the movie freq variable to lammps, you should pass the freq variable as the lammps movie frequency input** 
I see!  in in.lammps.template, in dump setting, instead of USERINPUT_MOVIE_FRQ I should pass  USERINPUT_SAMPLE_FRQ. Should I do it or @kadupitiya will do it?

**Comment by kadupitiya** [comment]
IMO, USERINPUT_MOVIE_FRQ is also important to pass right. We can create an additional parameter pass. Let's say USERINPUT_SAMPLE_FRQ. What about the timestep parameter?

**Comment by jadhao** [comment]
@nasimanousheh @kadupitiya 
No need to create a new variable. The key is to note that for lammps your movie freq is really the sampling freq based on how nasim has coded the script. It produces the movie which is fine, but its primary goal is to make the density profile. So the change is just:
generateLammpsInputfile(ein, mdremote.freq, mdremote.hiteqm, (mdremote.steps - mdremote.hiteqm));
that is I replace passing mdremote.moviefreq with mdremote.freq
@nasimanousheh should do the change as she is comparing the 2 methods. and she would know if this is the only place the change needs to be or more places. @kadupitiya can oversee if this makes sense.
--
for timestep, that could be hard coded in both approaches for now. @nasimanousheh should confirm if 0.001 is a good choice for all the parameter choices. We know 0.0005 works as this has been tested. Does 0.001 work for 3:1 system? If unsure, revert and default to 0.0005, otherwise 0.001 is fine.

**Comment by kadupitiya** [comment]
@jadhao: Yeah that makes sense. But apart from this issue, we do need to pass the time step as well right?

**Comment by jadhao** [comment]
@kadupitiya I reverted back to 0.0005 as dt. It is default in inhouse and also in lammps. Dont think we need to pass this. Assuming this is not changed in the simulation outside of its initial setting, we should be good to go. I will request an install this afternoon.

**Comment by kadupitiya** [comment]
@jadhao: Please wait until I send a PR with an updated notebook. This would be for walltime issue.
Thank you.

**Pull request merged**
