### PR TITLE
-J true for density from lammps

### PR DESCRIPTION
**Pull request by nasimanousheh**
@jadhao 
@kadupitiya 
PR from my fork based on the latest code.

### CODE REVIEW

**Comment by jadhao** [comment]
@nasimanousheh @kadupitiya I added some changes on top of nasim's PR, please check if things are working. Then I approve

**Comment by kadupitiya** [comment]
@jadhao and @nasimanousheh: Why do we want to commit ljmovie.xyz(~80MB) file?

**Comment by kadupitiya** [comment]
@jadhao : Looks ok to me.

**Comment by jadhao** [comment]
@kadupitiya wait till I approve. Approved.

**Pull request merged**
